# Generated by Django 4.0.4 on 2022-05-31 13:32

import os

from django.contrib.auth.hashers import make_password
from django.db import migrations
from django.db.migrations.state import StateApps
from dotenv import load_dotenv

load_dotenv()

admin_schema = {
    "email": os.getenv("EMAIL"),
    "password": os.getenv("PASSWORD"),
    "first_name": os.getenv("FIRST_NAME"),
    "last_name": os.getenv("LAST_NAME"),
    "age": 0,
    "cpf": "00000000000",
    "phone": "00000000000",
    "is_staff": True,
}


def default_user_admin(app: StateApps, _):
    User = app.get_model("users", "User")
    admin_schema["password"] = make_password(admin_schema["password"])
    User.objects.create(**admin_schema)


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_phone"),
    ]

    operations = [migrations.RunPython(default_user_admin)]
