# Generated by Django 4.0.4 on 2022-05-26 16:30

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('room_categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('room_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.IntegerField()),
                ('available', models.BooleanField(default=True)),
                ('room_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='room_categories.roomcategory')),
            ],
        ),
    ]
